### ISSUE TITLE
Crashes after adding marker in TPP signed 4.8.1 

### ISSUE THREAD

**Issue by FarrantAlex** [Cloud-RF/SOOTHSAYER-ATAK-plugin#5]
Spinner issue #4 was resolved with a proguard rule but now ATAK(!) crashes after adding a marker to the map.

06-09 11:33:22.101  8719  8719 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: java.lang.AbstractMethodError: abstract method "void com.atakmap.android.maps.ah$b.a(com.atakmap.android.maps.ak, com.atakmap.android.maps.ag)"
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.android.maps.ah.a(SourceFile:293)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.android.maps.an.e(SourceFile:298)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.android.maps.an.onDown(SourceFile:616)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:652)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.android.maps.an.onTouch(SourceFile:511)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.android.maps.MapView$2.a(SourceFile:216)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.map.AtakMapView.onTouchEvent(SourceFile:954)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:15014)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4283)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.atakmap.android.metrics.activity.MetricFragmentActivity.dispatchTouchEvent(SourceFile:86)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:15273)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6551)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6351)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5807)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5864)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5830)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5995)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5838)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6052)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5811)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5864)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5830)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5838)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5811)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8867)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8818)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8786)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8990)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:268)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:335)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.os.Looper.loopOnce(Looper.java:161)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:288)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:7944)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-09 11:33:22.103  8719  8719 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
06-09 11:33:22.103  8719  8719 D AndroidRuntime: Shutting down VM
06-09 11:33:22.104  8719  8719 E AndroidRuntime: FATAL EXCEPTION: main
06-09 11:33:22.104  8719  8719 E AndroidRuntime: Process: com.atakmap.app.civ, PID: 8719

**Comment by FarrantAlex** [comment]
{"TAK.sessionid":"e1669ea5-f51e-4c8b-a4b2-4610639d21d7",
"TAK.uid":"ANDROID-a7ccd4b8ee8462af",
"timestamp":"2023-06-14T20:51:29Z",
"os.version":"4.9.227-perf-22875358",
"android.release":"11",
"android.sdk":"30",
"device.model":"SM-T290",
"device.manufacturer":"samsung",
"ACRA.version":"4.6.1",
"TAK.brand":"CIV",
"TAK.version":"4.8.1.25 (e4d49f15)[playstore]",
"TAK.revision":"1685830888",
"TAK.plugin-api":"com.atakmap.app@4.8.1.CIV",
"TAK.error":"java.lang.AbstractMethodError: abstract method 'void com.atakmap.android.maps.ah$b.a(com.atakmap.android.maps.ak, com.atakmap.android.maps.ag)'",
"TAK.stackHash":"f89c5a2",
"system.plugins": [],
"plugins":[{"plugin":"plugin.version.loaded.SOOTHSAYER","version":"1.0 () - [4.8.1]-1"}

**Comment by FarrantAlex** [comment]
Fixed by upgrading gradle to 7.3.3
